package com.yrx.phoenix.entity;

import java.util.Date;

public class Article {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.id
     *
     * @mbg.generated Thu Feb 14 23:49:15 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.title
     *
     * @mbg.generated Thu Feb 14 23:49:15 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.outline
     *
     * @mbg.generated Thu Feb 14 23:49:15 CST 2019
     */
    private String outline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.category
     *
     * @mbg.generated Thu Feb 14 23:49:15 CST 2019
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.update_time
     *
     * @mbg.generated Thu Feb 14 23:49:15 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.rowkey
     *
     * @mbg.generated Thu Feb 14 23:49:15 CST 2019
     */
    private String rowkey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.id
     *
     * @return the value of article.id
     *
     * @mbg.generated Thu Feb 14 23:49:15 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.id
     *
     * @param id the value for article.id
     *
     * @mbg.generated Thu Feb 14 23:49:15 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.title
     *
     * @return the value of article.title
     *
     * @mbg.generated Thu Feb 14 23:49:15 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.title
     *
     * @param title the value for article.title
     *
     * @mbg.generated Thu Feb 14 23:49:15 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.outline
     *
     * @return the value of article.outline
     *
     * @mbg.generated Thu Feb 14 23:49:15 CST 2019
     */
    public String getOutline() {
        return outline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.outline
     *
     * @param outline the value for article.outline
     *
     * @mbg.generated Thu Feb 14 23:49:15 CST 2019
     */
    public void setOutline(String outline) {
        this.outline = outline == null ? null : outline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.category
     *
     * @return the value of article.category
     *
     * @mbg.generated Thu Feb 14 23:49:15 CST 2019
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.category
     *
     * @param category the value for article.category
     *
     * @mbg.generated Thu Feb 14 23:49:15 CST 2019
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.update_time
     *
     * @return the value of article.update_time
     *
     * @mbg.generated Thu Feb 14 23:49:15 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.update_time
     *
     * @param updateTime the value for article.update_time
     *
     * @mbg.generated Thu Feb 14 23:49:15 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.rowkey
     *
     * @return the value of article.rowkey
     *
     * @mbg.generated Thu Feb 14 23:49:15 CST 2019
     */
    public String getRowkey() {
        return rowkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.rowkey
     *
     * @param rowkey the value for article.rowkey
     *
     * @mbg.generated Thu Feb 14 23:49:15 CST 2019
     */
    public void setRowkey(String rowkey) {
        this.rowkey = rowkey == null ? null : rowkey.trim();
    }
}