package com.yrx.phoenix.entity;

import java.util.Date;

public class Content {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.id
     *
     * @mbg.generated Tue Feb 19 19:43:36 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.update_time
     *
     * @mbg.generated Tue Feb 19 19:43:36 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.insert_time
     *
     * @mbg.generated Tue Feb 19 19:43:36 CST 2019
     */
    private Date insertTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.content
     *
     * @mbg.generated Tue Feb 19 19:43:36 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.id
     *
     * @return the value of content.id
     *
     * @mbg.generated Tue Feb 19 19:43:36 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.id
     *
     * @param id the value for content.id
     *
     * @mbg.generated Tue Feb 19 19:43:36 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.update_time
     *
     * @return the value of content.update_time
     *
     * @mbg.generated Tue Feb 19 19:43:36 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.update_time
     *
     * @param updateTime the value for content.update_time
     *
     * @mbg.generated Tue Feb 19 19:43:36 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.insert_time
     *
     * @return the value of content.insert_time
     *
     * @mbg.generated Tue Feb 19 19:43:36 CST 2019
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.insert_time
     *
     * @param insertTime the value for content.insert_time
     *
     * @mbg.generated Tue Feb 19 19:43:36 CST 2019
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.content
     *
     * @return the value of content.content
     *
     * @mbg.generated Tue Feb 19 19:43:36 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.content
     *
     * @param content the value for content.content
     *
     * @mbg.generated Tue Feb 19 19:43:36 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}