package com.yrx.phoenix.entity;

import java.util.Date;

public class TagInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_info.id
     *
     * @mbg.generated Wed Feb 20 21:34:01 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_info.article_id
     *
     * @mbg.generated Wed Feb 20 21:34:01 CST 2019
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_info.tag
     *
     * @mbg.generated Wed Feb 20 21:34:01 CST 2019
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_info.update_time
     *
     * @mbg.generated Wed Feb 20 21:34:01 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_info.insert_time
     *
     * @mbg.generated Wed Feb 20 21:34:01 CST 2019
     */
    private Date insertTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_info.id
     *
     * @return the value of tag_info.id
     *
     * @mbg.generated Wed Feb 20 21:34:01 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_info.id
     *
     * @param id the value for tag_info.id
     *
     * @mbg.generated Wed Feb 20 21:34:01 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_info.article_id
     *
     * @return the value of tag_info.article_id
     *
     * @mbg.generated Wed Feb 20 21:34:01 CST 2019
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_info.article_id
     *
     * @param articleId the value for tag_info.article_id
     *
     * @mbg.generated Wed Feb 20 21:34:01 CST 2019
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_info.tag
     *
     * @return the value of tag_info.tag
     *
     * @mbg.generated Wed Feb 20 21:34:01 CST 2019
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_info.tag
     *
     * @param tag the value for tag_info.tag
     *
     * @mbg.generated Wed Feb 20 21:34:01 CST 2019
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_info.update_time
     *
     * @return the value of tag_info.update_time
     *
     * @mbg.generated Wed Feb 20 21:34:01 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_info.update_time
     *
     * @param updateTime the value for tag_info.update_time
     *
     * @mbg.generated Wed Feb 20 21:34:01 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_info.insert_time
     *
     * @return the value of tag_info.insert_time
     *
     * @mbg.generated Wed Feb 20 21:34:01 CST 2019
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_info.insert_time
     *
     * @param insertTime the value for tag_info.insert_time
     *
     * @mbg.generated Wed Feb 20 21:34:01 CST 2019
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }
}