package com.yrx.phoenix.dao.remote.tag;

import com.yrx.phoenix.entity.TagInfo;
import com.yrx.phoenix.entity.TagInfoExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface TagInfoMapperRemote {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbg.generated Wed Feb 20 21:34:01 CST 2019
     */
    @SelectProvider(type= TagInfoSqlProviderRemote.class, method="countByExample")
    long countByExample(TagInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbg.generated Wed Feb 20 21:34:01 CST 2019
     */
    @DeleteProvider(type= TagInfoSqlProviderRemote.class, method="deleteByExample")
    int deleteByExample(TagInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbg.generated Wed Feb 20 21:34:01 CST 2019
     */
    @Insert({
        "insert into tag_info (article_id, tag, ",
        "update_time, insert_time)",
        "values (#{articleId,jdbcType=INTEGER}, #{tag,jdbcType=VARCHAR}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{insertTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(TagInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbg.generated Wed Feb 20 21:34:01 CST 2019
     */
    @InsertProvider(type= TagInfoSqlProviderRemote.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(TagInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbg.generated Wed Feb 20 21:34:01 CST 2019
     */
    @SelectProvider(type= TagInfoSqlProviderRemote.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER),
        @Result(column="article_id", property="articleId", jdbcType=JdbcType.INTEGER),
        @Result(column="tag", property="tag", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="insert_time", property="insertTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<TagInfo> selectByExample(TagInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbg.generated Wed Feb 20 21:34:01 CST 2019
     */
    @UpdateProvider(type= TagInfoSqlProviderRemote.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TagInfo record, @Param("example") TagInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbg.generated Wed Feb 20 21:34:01 CST 2019
     */
    @UpdateProvider(type= TagInfoSqlProviderRemote.class, method="updateByExample")
    int updateByExample(@Param("record") TagInfo record, @Param("example") TagInfoExample example);
}